[package]
name = "core"
version = "2.0.1"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.9.1"
log = "0.4.27"
